name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.5'

      -
        name: Setup Redis
        uses: zhulik/redis-action@1.1.0
        with:
          redis version: latest

      -
        name: Check out code into the Go module directory
        uses: actions/checkout@v4

      -
        name: Get dependencies
        run: go mod download

      -
        name: Test
        run: go test ./...

      -
        name: Build
        if: success()
        env:
          CGO_ENABLED: 0
        run: |
          go build -o apiserver -v ./cmd/apiserver
          go build -o landingserver -v ./cmd/landingserver
          go build -o createuser -v ./cmd/createuser
          go build -o migraterequesthistory -v ./cmd/migraterequesthistory
